version: "3.7"
services:

  prometheus_exporter:
    image: tomcatengineering/docker_swarm_exporter
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "9675:9675/tcp"
